version: '3.5'
services:
  go-course-enrollment:
    platform: linux/amd64
    container_name: go-course-enrollment
    build:
      context: ./.dockers/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_course_enrollment
    ports:
      - "3323:3306"
    volumes:
      - ./.dockers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql